server {
    listen 20080;
    root /usr/share/nginx/html;
    index index.html;

    location /_nuxt/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
