name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Deploy
        run: ssh -p22 metastruct@threekelv.in test-github
